
Style/FileName:
  Exclude:
    - lib/rubocop-yast.rb

# align arrows:
# "foo"     => true
# "foo_bar" => false
Style/AlignHash:
  EnforcedHashRocketStyle: table

# no extra indentation for multiline function calls
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# no extra indentation for case
Style/CaseIndentation:
  IndentWhenRelativeTo: end

# disabled, unless should be used only in trailing form
Style/NegatedIf:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# use "raise" instead of "fail"
Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

