Yast/Builtins:
  Description: "Check for obsolete Builtins.* calls"
  Enabled: true

Yast/Ops:
  Description: "Check for obsolete Ops.* calls"
  Enabled: true
  StrictMode: true

Yast/LogVariable:
  Description: "Check for using 'log' variable"
  Enabled: true
